/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Card: typeof import('./inertia/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./inertia/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./inertia/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./inertia/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./inertia/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./inertia/components/ui/card/CardTitle.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Progress: typeof import('./inertia/components/ui/progress/Progress.vue')['default']
    RadioGroup: typeof import('./inertia/components/ui/radio-group/RadioGroup.vue')['default']
    RadioGroupItem: typeof import('./inertia/components/ui/radio-group/RadioGroupItem.vue')['default']
  }
}
